crud_mine/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

crud_mine/tasks/urls.py
#-*- coding:utf-8 -*-

from django.urls import path, re_path
from . import views

# namespace
app_name = 'tasks'

urlpatterns = [
    # Create a task
    path('create/', views.TaskCreateView.as_view(), name='task_create'),
    # Retrieve task list
    path('', views.TaskListView.as_view(), name='task_list'),
    # Retrieve single task object
    re_path(r'^(?P<pk>\d+)/$', views.TaskDetailView.as_view(), name='task_detail'),
    # Update a task
    re_path(r'^(?P<pk>\d+)/update/$', views.TaskUpdateView.as_view(), name='task_update'),
    # Delete a task
    re_path(r'^(?P<pk>\d+)/delete/$', views.TaskDeleteView.as_view(), name='task_delete')

    # # Create a task
    # path('create/', views.task_create, name='task_create'),
    # # Retrieve task list
    # path('', views.task_list, name='task_list'),
    # # Retrieve single task object
    # re_path(r'^(?P<pk>\d+)/$', views.task_detail, name='task_detail'),
    # # Update a task
    # re_path(r'^(?P<pk>\d+)/update/$', views.task_update, name='task_update'),
    # # Delete a task
    # re_path(r'^(?P<pk>\d+)/delete/$', views.task_delete, name='task_delete'),

]

crud_mine/tasks/models.py
from django.db import models


# Create your models here.

class Status(models.TextChoices):
    NOTSTARTED = 'u', "Tarea no iniciada"
    ONGOING = 'o', "Trabajando"
    FINISHED = 'f', "Finalizada"


class Task(models.Model):
    name = models.CharField(verbose_name="Nombre", max_length=65, unique=True)
    status = models.CharField(verbose_name="Estado", max_length=1, choices=Status.choices)

    def __str__(self):
        return self.name

crud_mine/tasks/forms.py
from .models import Task
from django import forms


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = "__all__"

crud_mine/tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Task
from .forms import TaskForm

from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView

class TaskListView(ListView):
    model = Task
    context_object_name = 'tasks'

class TaskDetailView(DetailView):
    model = Task

class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:task_list')

class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')

crud_mine/tasks/templates/tasks/task_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>¿Está seguro que desea eliminar? "{{ task }}"?</p>
    <input type="submit" value="Confirm" />
</form>

crud_mine/tasks/templates/tasks/task_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detalle de la Tarea</title>
</head>
<body>
<p> Nombre de la Tarea: {{ task.name }} | <a href="{% url 'tasks:task_update' task.id %}">Actualizar</a> |
    <a href="{% url 'tasks:task_delete' task.id %}">Eliminar</a>
</p>
<p> Estado de la Tarea: {{ task.get_status_display }} </p>
<p> <a href="{% url 'tasks:task_list' %}">Ver todas las tareas</a> |
    <a href="{% url 'tasks:task_create'%}">Nueva Tarea</a>
</p>
</body>
</html>

crud_mine/tasks/templates/tasks/task_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% if object %}Editar Tarea {% else %} Cree una nueva Tarea {% endif %}</title>
</head>

<body>
    <h3>{% if object %}Editar Tarea {% else %} Cree una nueva Tarea {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</body>

</html>

crud_mine/tasks/templates/tasks/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de Tareas</title>
</head>
<body>
<h3>Lista de Tareas</h3>
{% for task in tasks %}
    <p>{{ forloop.counter }}. {{ task.name }} - {{ task.get_status_display }}
        (<a href="{% url 'tasks:task_update' task.id %}">Actualizar</a> |
        <a href="{% url 'tasks:task_delete' task.id %}">Eliminar</a>)
    </p>
{% endfor %}

<p> <a href="{% url 'tasks:task_create' %}"> + Agregar una nueva Tarea</a></p>
</body>
</html>